apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'kubepocket'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - kubepocket
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: kubepocket
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: metrics
      - source_labels: [__address__, __meta_kubernetes_endpoint_port_number]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 15s\n  evaluation_interval: 15s\n\nscrape_configs:\n- job_name: 'kubepocket'\n  kubernetes_sd_configs:\n  - role: endpoints\n    namespaces:\n      names:\n      - kubepocket\n  relabel_configs:\n  - source_labels: [__meta_kubernetes_service_label_app]\n    action: keep\n    regex: kubepocket\n  - source_labels: [__meta_kubernetes_endpoint_port_name]\n    action: keep\n    regex: metrics\n  - source_labels: [__address__, __meta_kubernetes_endpoint_port_number]\n    action: replace\n    regex: ([^:]+)(?::\\d+)?;(\\d+)\n    replacement: $1:$2\n    target_label: __address__\n  - source_labels: [__meta_kubernetes_namespace]\n    target_label: namespace\n  - source_labels: [__meta_kubernetes_service_name]\n    target_label: service\n  - source_labels: [__meta_kubernetes_pod_name]\n    target_label: pod\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-config","namespace":"monitoring"}}
  creationTimestamp: "2026-02-14T15:14:58Z"
  name: prometheus-config
  namespace: monitoring
  resourceVersion: "656"
  uid: 3fe839e6-2fa1-44da-a408-70f2da588560
