{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubepocket.fullname" . }}-reader-binding
  labels:
    {{- include "kubepocket.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubepocket.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubepocket.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
