apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubepocket.fullname" . }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubepocket.labels" . | nindent 4 }}
type: Opaque
stringData:
  config: |
    {{ .Files.Get "kubeconfig.yaml" | nindent 4 }}
