apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubepocket.fullname" . }}-collector
  labels:
    {{- include "kubepocket.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubepocket.fullname" . }}-collector
  labels:
    {{- include "kubepocket.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubepocket.fullname" . }}-collector
  labels:
    {{- include "kubepocket.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubepocket.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubepocket.fullname" . }}-collector
  apiGroup: rbac.authorization.k8s.io